//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDVintageModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Articulo()
        {
            this.tb_LineaPedido = new HashSet<tb_LineaPedido>();
        }
    
        public int no_articulo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> existencia { get; set; }
        public Nullable<double> Precio { get; set; }
        public string Descrip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_LineaPedido> tb_LineaPedido { get; set; }
    }
}
