//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDVintageModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_LineaPedido
    {
        public int no_Pedido { get; set; }
        public int no_articulo { get; set; }
        public Nullable<int> unidades { get; set; }
        public Nullable<double> precio_Unidad { get; set; }
        public Nullable<double> precio_Total { get; set; }
        public int no_Compra { get; set; }
    
        public virtual tb_Articulo tb_Articulo { get; set; }
        public virtual tb_Encabezado tb_Encabezado { get; set; }
    }
}
