//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Receta()
        {
            this.tb_Favoritos = new HashSet<tb_Favoritos>();
            this.tb_Historial = new HashSet<tb_Historial>();
        }
    
        public int pkReceta { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> Dfecha_publicacion { get; set; }
        public string vTexto { get; set; }
        public string vimgurl { get; set; }
        public string vVidurl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Favoritos> tb_Favoritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Historial> tb_Historial { get; set; }
    }
}
