//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BDVintageModel;    
    public partial class ConexionVintage : DbContext,IDisposable
    {
        public ConexionVintage()
            : base("name=ConexionVintage")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Articulo> tb_Articulo { get; set; }
        public virtual DbSet<tb_Cliente> tb_Cliente { get; set; }
        public virtual DbSet<tb_Direccion> tb_Direccion { get; set; }
        public virtual DbSet<tb_Encabezado> tb_Encabezado { get; set; }
        public virtual DbSet<tb_Favoritos> tb_Favoritos { get; set; }
        public virtual DbSet<tb_Historial> tb_Historial { get; set; }
        public virtual DbSet<tb_LineaPedido> tb_LineaPedido { get; set; }
        public virtual DbSet<tb_Receta> tb_Receta { get; set; }
    }
}
