//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Cliente()
        {
            this.tb_Encabezado = new HashSet<tb_Encabezado>();
            this.tb_Favoritos = new HashSet<tb_Favoritos>();
            this.tb_Historial = new HashSet<tb_Historial>();
        }
    
        public int id_Cliente { get; set; }
        public string vNombre { get; set; }
        public string vApellido { get; set; }
        public string vApelldo2 { get; set; }
        public string vContra { get; set; }
        public Nullable<int> iEdad { get; set; }
        public int id_direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Encabezado> tb_Encabezado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Favoritos> tb_Favoritos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Historial> tb_Historial { get; set; }
        public virtual tb_Direccion tb_Direccion { get; set; }
    }
}
