//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Historial
    {
        public int pkHistorial { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int iCliente_id { get; set; }
        public int fkReceta { get; set; }
    
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_Receta tb_Receta { get; set; }
    }
}
